package com.servicepro.entities;
// Generated Nov 6, 2020, 2:05:45 AM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.*;

/**
 * Address generated by hbm2java
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@Entity
@Table(name = "address", catalog = "servicebyprodb")
public class Address implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2650894977332985986L;
	private Integer idAddress;
	private String wilaya;
	private String commune;
	private float latitude;
	private float longitude;
	@JsonIgnore
	private Set<Work> works = new HashSet<Work>(0);
	@JsonIgnore
	private Set<User> users = new HashSet<User>(0);

	public Address() {
	}

	public Address(String wilaya, String commune, float latitude, float longitude) {
		this.wilaya = wilaya;
		this.commune = commune;
		this.latitude = latitude;
		this.longitude = longitude;
	}

	public Address(String wilaya, String commune, float latitude, float longitude, Set<Work> works, Set<User> users) {
		this.wilaya = wilaya;
		this.commune = commune;
		this.latitude = latitude;
		this.longitude = longitude;
		this.works = works;
		this.users = users;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_address", unique = true, nullable = false)
	public Integer getIdAddress() {
		return this.idAddress;
	}

	public void setIdAddress(Integer idAddress) {
		this.idAddress = idAddress;
	}

	@Column(name = "wilaya", nullable = false, length = 50)
	public String getWilaya() {
		return this.wilaya;
	}

	public void setWilaya(String wilaya) {
		this.wilaya = wilaya;
	}

	@Column(name = "commune", nullable = false, length = 50)
	public String getCommune() {
		return this.commune;
	}

	public void setCommune(String commune) {
		this.commune = commune;
	}

	@Column(name = "latitude", nullable = false, precision = 10, scale = 6)
	public float getLatitude() {
		return this.latitude;
	}

	public void setLatitude(float latitude) {
		this.latitude = latitude;
	}

	@Column(name = "longitude", nullable = false, precision = 10, scale = 6)
	public float getLongitude() {
		return this.longitude;
	}

	public void setLongitude(float longitude) {
		this.longitude = longitude;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "address")
	public Set<Work> getWorks() {
		return this.works;
	}

	public void setWorks(Set<Work> works) {
		this.works = works;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "address")
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

}
