package com.servicepro.entities;
// Generated Nov 6, 2020, 2:05:45 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Application generated by hbm2java
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@Entity
@Table(name = "application", catalog = "servicebyprodb")
public class Application implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3607518043943192316L;
	private Integer idApplication;
	private User user;
	//@JsonIgnore
	@JsonBackReference
	private Work work;
	private String status;

	public Application() {
	}

	public Application(User user, Work work, String status) {
		this.user = user;
		this.work = work;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_application", unique = true, nullable = false)
	public Integer getIdApplication() {
		return this.idApplication;
	}

	public void setIdApplication(Integer idApplication) {
		this.idApplication = idApplication;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_artisan", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_work", nullable = false)
	public Work getWork() {
		return this.work;
	}

	public void setWork(Work work) {
		this.work = work;
	}

	@Column(name = "status", nullable = false, length = 8)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
