package com.servicepro.entities;
// Generated Nov 6, 2020, 2:05:45 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.*;

/**
 * Review generated by hbm2java
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@Entity
@Table(name = "review", catalog = "servicebyprodb")
public class Review implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 979395507940503936L;
	private Integer idReview;
	//@JsonBackReference(value="review-user")
	private User user;
	//@JsonBackReference(value="review-wor
	private Work work;
	private String title;
	private String body;
	private int rating;
	@JsonFormat(pattern="yyyy-MM-dd'T'HH:mm:ss", timezone="CET")
	private Date reviewDate;

	public Review() {
	}

	public Review(User user, Work work, String title, String body, int rating, Date reviewDate) {
		this.user = user;
		this.work = work;
		this.title = title;
		this.body = body;
		this.rating = rating;
		this.reviewDate = reviewDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_review", unique = true, nullable = false)
	public Integer getIdReview() {
		return this.idReview;
	}

	public void setIdReview(Integer idReview) {
		this.idReview = idReview;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_reviewer", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_work", nullable = false)
	public Work getWork() {
		return this.work;
	}

	public void setWork(Work work) {
		this.work = work;
	}

	@Column(name = "title", nullable = false, length = 100)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "body", nullable = false)
	public String getBody() {
		return this.body;
	}

	public void setBody(String body) {
		this.body = body;
	}

	@Column(name = "rating", nullable = false)
	public int getRating() {
		return this.rating;
	}

	public void setRating(int rating) {
		this.rating = rating;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "review_date", nullable = false, length = 19)
	public Date getReviewDate() {
		return this.reviewDate;
	}

	public void setReviewDate(Date reviewDate) {
		this.reviewDate = reviewDate;
	}

}
