package com.servicepro.entities;
// Generated Nov 6, 2020, 2:05:45 AM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Service generated by hbm2java
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@Entity
@Table(name = "service", catalog = "servicebyprodb", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class Service implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6183792593552418550L;
	private Integer idService;
	private Categorie categorie;
	private String name;
	private String status;
	@JsonIgnore
	private Set<User> users = new HashSet<User>(0);
	@JsonIgnore
	private Set<Work> works = new HashSet<Work>(0);

	public Service() {
	}

	public Service(Categorie categorie, String name, String status) {
		this.categorie = categorie;
		this.name = name;
		this.status = status;
	}

	public Service(Categorie categorie, String name, String status, Set<User> users, Set<Work> works) {
		this.categorie = categorie;
		this.name = name;
		this.status = status;
		this.users = users;
		this.works = works;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_service", unique = true, nullable = false)
	public Integer getIdService() {
		return this.idService;
	}

	public void setIdService(Integer idService) {
		this.idService = idService;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_categorie", nullable = false)
	public Categorie getCategorie() {
		return this.categorie;
	}

	public void setCategorie(Categorie categorie) {
		this.categorie = categorie;
	}

	@Column(name = "name", unique = true, nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "status", nullable = false, length = 11)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@ManyToMany(fetch = FetchType.EAGER)
	@JoinTable(name = "services_artisan", catalog = "servicebyprodb", joinColumns = {
			@JoinColumn(name = "id_service", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "id_artisan", nullable = false, updatable = false) })
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "service")
	public Set<Work> getWorks() {
		return this.works;
	}

	public void setWorks(Set<Work> works) {
		this.works = works;
	}

}
